### ISSUE TITLE
Sentinels who are Guarding Dont TP To other worlds.

### ISSUE THREAD

**Issue by chrissquid1245** [mcmonkey4eva/Sentinel#138]
I'm using Sentinel Version 0.8 on my 1.10.2 Server. When i have an npc guarding someone if that person teleports to another world the Guard does not teleport to the person.

**Comment by mcmonkey4eva** [comment]
Update to 1.11.2

**Comment by chrissquid1245** [comment]
ok thanks for the response!

**Comment by chrissquid1245** [comment]
I updated to 1.11.2 and still the Guards will not teleport between worlds. Could this be an issue with Citizens and not Sentinel?

**Comment by mcmonkey4eva** [comment]
If you've updated Sentinel to latest dev release, and it doesn't follow between worlds, there may be a bug

**Comment by chrissquid1245** [comment]
Where can i find the latest dev release?

**Comment by BloodEko** [comment]
http://ci.citizensnpcs.co/job/Sentinel/

**Comment by jaggy80** [comment]
I am also getting this issue with latest dev releases:
Citizens version: 2.0.21-SNAPSHOT (build 1472)
Sentinel version: 1.0 (build 104)

[17:14:14 INFO]: [Citizens] Exception while updating 41: Cannot measure distance between Hub and Survival.
[17:14:14 WARN]: java.lang.IllegalArgumentException: Cannot measure distance between Hub and Survival
[17:14:14 WARN]:        at org.bukkit.Location.distanceSquared(Location.java:456)
[17:14:14 WARN]:        at org.mcmonkey.sentinel.SentinelTrait.findBestTarget(SentinelTrait.java:1506)
[17:14:14 WARN]:        at org.mcmonkey.sentinel.SentinelTrait.runUpdate(SentinelTrait.java:1585)
[17:14:14 WARN]:        at org.mcmonkey.sentinel.SentinelTrait.run(SentinelTrait.java:1717)
[17:14:14 WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:430)
[17:14:14 WARN]:        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:268)
[17:14:14 WARN]:        at net.citizensnpcs.nms.v1_11_R1.entity.EntityHumanNPC.A_(EntityHumanNPC.java:140)
[17:14:14 WARN]:        at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1629)
[17:14:14 WARN]:        at net.citizensnpcs.nms.v1_11_R1.util.NMSImpl.tick(NMSImpl.java:999)
[17:14:14 WARN]:        at net.citizensnpcs.util.NMS.tick(NMS.java:270)
[17:14:14 WARN]:        at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36)
[17:14:14 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[17:14:14 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[17:14:14 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738)
[17:14:14 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[17:14:14 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[17:14:14 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[17:14:14 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by mcmonkey4eva** [comment]
Oh woops, fixed that in latest dev build - 105

**Comment by jaggy80** [comment]
Just tried 105.. same results.  appreciate your time

**Comment by mcmonkey4eva** [comment]
If nothing else at least post an updated error log.

It's logically impossible for the new version to result in the /exact/ same message.

**Comment by jaggy80** [comment]
Just realized the error is diff:

[17:39:48 INFO]: [Citizens] Exception while updating 42: Cannot measure distance between Hub and Survival.
[17:39:48 WARN]: java.lang.IllegalArgumentException: Cannot measure distance between Hub and Survival
[17:39:48 WARN]:        at org.bukkit.Location.distanceSquared(Location.java:456)
[17:39:48 WARN]:        at net.citizensnpcs.api.ai.TeleportStuckAction.run(TeleportStuckAction.java:26)
[17:39:48 WARN]:        at net.citizensnpcs.npc.ai.CitizensNavigator.stopNavigating(CitizensNavigator.java:309)
[17:39:48 WARN]:        at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:158)
[17:39:48 WARN]:        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:274)
[17:39:48 WARN]:        at net.citizensnpcs.nms.v1_11_R1.entity.EntityHumanNPC.A_(EntityHumanNPC.java:140)
[17:39:48 WARN]:        at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1629)
[17:39:48 WARN]:        at net.citizensnpcs.nms.v1_11_R1.util.NMSImpl.tick(NMSImpl.java:999)
[17:39:48 WARN]:        at net.citizensnpcs.util.NMS.tick(NMS.java:270)
[17:39:48 WARN]:        at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36)
[17:39:48 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[17:39:48 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[17:39:48 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738)
[17:39:48 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[17:39:48 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[17:39:48 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[17:39:48 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by mcmonkey4eva** [comment]
Aha, that one is partially Citizens fault, but I've corrected for it locally. Fix is in build dev 106.

**Comment by jaggy80** [comment]
Build 106 looks like the same as previous error.. i went over it twice and looks exactly the same.. sorry if it's spammy:

[17:51:02 INFO]: [Citizens] Exception while updating 42: Cannot measure distance between Hub and Survival.
[17:51:02 WARN]: java.lang.IllegalArgumentException: Cannot measure distance between Hub and Survival
[17:51:02 WARN]:        at org.bukkit.Location.distanceSquared(Location.java:456)
[17:51:02 WARN]:        at net.citizensnpcs.api.ai.TeleportStuckAction.run(TeleportStuckAction.java:26)
[17:51:02 WARN]:        at net.citizensnpcs.npc.ai.CitizensNavigator.stopNavigating(CitizensNavigator.java:309)
[17:51:02 WARN]:        at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:158)
[17:51:02 WARN]:        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:274)
[17:51:02 WARN]:        at net.citizensnpcs.nms.v1_11_R1.entity.EntityHumanNPC.A_(EntityHumanNPC.java:140)
[17:51:02 WARN]:        at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1629)
[17:51:02 WARN]:        at net.citizensnpcs.nms.v1_11_R1.util.NMSImpl.tick(NMSImpl.java:999)
[17:51:02 WARN]:        at net.citizensnpcs.util.NMS.tick(NMS.java:270)
[17:51:02 WARN]:        at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36)
[17:51:02 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[17:51:02 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[17:51:02 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738)
[17:51:02 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[17:51:02 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[17:51:02 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[17:51:02 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by mcmonkey4eva** [comment]
If cancelling the navigation order while moving  between works isn't enough to shut up the stuck action error, it's a Citizens error D:

**Comment by jaggy80** [comment]
D:  let me know if there's any info or testing that would help.  The old Sentry plugin worked, but I know a lot has changed

**Comment by mcmonkey4eva** [comment]
I've submitted https://github.com/CitizensDev/CitizensAPI/pull/25 for review. Once that gets pulled, it should fix the bug. Or, at least, this latest bug in a series of bugs... heh.

**Comment by mcmonkey4eva** [comment]
Try latest build of Citizens, my update has been included :)

**Comment by jaggy80** [comment]
Well, no more errors :)  but NPC isn't following between worlds now..  I believe it's staying in source world, but not sure how to check an npc's current coords.  After doing /citizens save, it shows the NPC is still in the source world even though I'm in another..  Getting closer though!

**Comment by mcmonkey4eva** [comment]
For that to happen in that way, the teleport has to have been blocked somehow...?

**Comment by jaggy80** [comment]
Getting weird results testing with just plugins citizens, sentinel, and multiverse.. finally got an error but not sure how related:
http://pastebin.com/vrk6E9PC

Seems like sometimes it does follow.. i'll try to get more info

**Comment by jaggy80** [comment]
Here's another one.. looks like an error about trying to attack cross world?

http://pastebin.com/sk8Qq0Y2

**Comment by mcmonkey4eva** [comment]
The latter error has been fixed, the first errors is Citizens or Minecraft level oddity I think...

Perhaps @fullwall can comment on http://pastebin.com/vrk6E9PC

**Comment by jaggy80** [comment]
Build 107 I can't get any errors now, but still can't see the NPC when I change worlds.. I turned on debug to file and path debugging.. nothing interesting in the file, but I see the dandelions for path finding, but NPC isn't visible and dandelion path just gets longer the further I go.  Dandelions not generating in the destination world, only the source.  Can see NPC in source world until I TP to destination once.  /citizens reload makes NPC visible in source again.

**Comment by chrissquid1245** [comment]
Same thing is happening to me. When the guard follows to me a different world it is not visible. And when i do /npc tp it teleports me to where the guard should be yet its invisible.

**Comment by chrissquid1245** [comment]
If you find out a reason why the npcs are invisible between worlds please let me know.

**Comment by mcmonkey4eva** [comment]
Still waiting for fullwall - he hasn't been online in about 9 days .-.

**Comment by jaggy80** [comment]
How dare fullwall consider his personal life and family more important than his code.  Blasphemy.

**Comment by fullwall** [comment]
The error is pretty strange... are we sure it's related?

**Comment by mcmonkey4eva** [comment]
is this still an issue in 1.12?

**Comment by jaggy80** [comment]
Same errors spam console on 1.12 when you /mv tp to another world with a sentinel guarding you:

[Citizens] Exception while updating 50: Cannot measure distance between Hub and Survival.
[https://pastebin.com/vftj304m](url)

Sorry for slow reply/test

**Comment by mcmonkey4eva** [comment]
That one's sourced from Citizens for sure - post it on that github please.
