### ISSUE TITLE
Guards Attacking each other

### ISSUE THREAD

**Issue by tharvoil** [mcmonkey4eva/Sentinel#83]
I have guards set up in common areas to target monsters and the pvp event. I've also added the ignore for npcs as well as specific npcs with the name "Guard" as well(which all guards are named). The issue I'm seeing is that if one accidentally hits one when trying to attack a monster or player, they will then turn and fight each other. They then continue to attack each other forever until a server restart. The log tends to get spammed with the following as well, not sure if this is a citizens issue or a sentinel issue though:
```
[19:26:25] [Server thread/INFO]: [Citizens] Exception while updating 34: null.
[19:26:25] [Server thread/WARN]: java.lang.NullPointerException
[19:26:25] [Server thread/WARN]: 	at org.mcmonkey.sentinel.SentinelTrait.fireArrow(SentinelTrait.java:462)
[19:26:25] [Server thread/WARN]: 	at org.mcmonkey.sentinel.SentinelTrait.tryAttack(SentinelTrait.java:898)
[19:26:25] [Server thread/WARN]: 	at org.mcmonkey.sentinel.SentinelTrait.runUpdate(SentinelTrait.java:1341)
[19:26:25] [Server thread/WARN]: 	at org.mcmonkey.sentinel.SentinelTrait.run(SentinelTrait.java:1422)
[19:26:25] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:430)
[19:26:25] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:270)
[19:26:25] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_10_R1.entity.EntityHumanNPC.m(EntityHumanNPC.java:309)
[19:26:25] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1629)
[19:26:25] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.World.g(World.java:1604)
[19:26:25] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_10_R1.util.NMSImpl.tick(NMSImpl.java:830)
[19:26:25] [Server thread/WARN]: 	at net.citizensnpcs.util.NMS.tick(NMS.java:246)
[19:26:25] [Server thread/WARN]: 	at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36)
[19:26:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
[19:26:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[19:26:25] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723)
[19:26:25] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
[19:26:25] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[19:26:25] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[19:26:25] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

**Comment by mcmonkey4eva** [comment]
Does this happen on latest dev builds: http://ci.citizensnpcs.co/job/Sentinel/ ?

**Comment by tharvoil** [comment]
It does, I'm running the latest dev build. I've also tried adding them to a squad but that doesn't make a difference.

**Comment by mcmonkey4eva** [comment]
I pushed a new dev build (number 65) which should fix the NPE. As for NPCs attacking each other: I'm not sure why that would happen 0.o they shouldn't even swing at each other, definitely not target eachother with `npcs` in their ignore list

**Comment by tharvoil** [comment]
Don't see the NPE, still getting guards attacking each other. I recorded a video so you can see what happens. It's at https://youtu.be/Ny714P0Wwio

**Comment by mcmonkey4eva** [comment]
Do you have `safeshot` enabled on the NPCs?

**Comment by mcmonkey4eva** [comment]
Update: build 66 should patch the issue actually.

**Comment by tharvoil** [comment]
Looks like that fixed it, thanks for the quick work!
